/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as BrandRouteImport } from './routes/_brand'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as BrandLoginRouteImport } from './routes/_brand/login'
import { Route as BrandOnboardingRouteImport } from './routes/_brand/onboarding'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedProjectsProject_idRouteImport } from './routes/_authenticated/projects/$project_id'
import { Route as AuthenticatedProjectsProject_idIndexRouteImport } from './routes/_authenticated/projects/$project_id/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/_brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const BrandLoginRoute = BrandLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => BrandRoute,
} as any)
const BrandOnboardingRoute = BrandOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => BrandRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProject_idRoute =
  AuthenticatedProjectsProject_idRouteImport.update({
    id: '/projects/$project_id',
    path: '/projects/$project_id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProject_idIndexRoute =
  AuthenticatedProjectsProject_idIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProject_idRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof BrandLoginRoute
  '/onboarding': typeof BrandOnboardingRoute
  '/projects/$project_id': typeof AuthenticatedProjectsProject_idRouteWithChildren
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/projects/$project_id/': typeof AuthenticatedProjectsProject_idIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof BrandLoginRoute
  '/onboarding': typeof BrandOnboardingRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/projects/$project_id': typeof AuthenticatedProjectsProject_idIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_brand': typeof BrandRouteWithChildren
  '/_brand/login': typeof BrandLoginRoute
  '/_brand/onboarding': typeof BrandOnboardingRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/projects/$project_id': typeof AuthenticatedProjectsProject_idRouteWithChildren
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/projects/$project_id/': typeof AuthenticatedProjectsProject_idIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/projects/$project_id'
    | '/projects/'
    | '/projects/$project_id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/onboarding' | '/projects' | '/projects/$project_id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_brand'
    | '/_brand/login'
    | '/_brand/onboarding'
    | '/_authenticated/'
    | '/_authenticated/projects/$project_id'
    | '/_authenticated/projects/'
    | '/_authenticated/projects/$project_id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BrandRoute: typeof BrandRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_brand': {
      id: '/_brand'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_brand/login': {
      id: '/_brand/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof BrandLoginRouteImport
      parentRoute: typeof BrandRoute
    }
    '/_brand/onboarding': {
      id: '/_brand/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof BrandOnboardingRouteImport
      parentRoute: typeof BrandRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$project_id': {
      id: '/_authenticated/projects/$project_id'
      path: '/projects/$project_id'
      fullPath: '/projects/$project_id'
      preLoaderRoute: typeof AuthenticatedProjectsProject_idRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$project_id/': {
      id: '/_authenticated/projects/$project_id/'
      path: '/'
      fullPath: '/projects/$project_id/'
      preLoaderRoute: typeof AuthenticatedProjectsProject_idIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProject_idRoute
    }
  }
}

interface AuthenticatedProjectsProject_idRouteChildren {
  AuthenticatedProjectsProject_idIndexRoute: typeof AuthenticatedProjectsProject_idIndexRoute
}

const AuthenticatedProjectsProject_idRouteChildren: AuthenticatedProjectsProject_idRouteChildren =
  {
    AuthenticatedProjectsProject_idIndexRoute:
      AuthenticatedProjectsProject_idIndexRoute,
  }

const AuthenticatedProjectsProject_idRouteWithChildren =
  AuthenticatedProjectsProject_idRoute._addFileChildren(
    AuthenticatedProjectsProject_idRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProjectsProject_idRoute: typeof AuthenticatedProjectsProject_idRouteWithChildren
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProjectsProject_idRoute:
    AuthenticatedProjectsProject_idRouteWithChildren,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface BrandRouteChildren {
  BrandLoginRoute: typeof BrandLoginRoute
  BrandOnboardingRoute: typeof BrandOnboardingRoute
}

const BrandRouteChildren: BrandRouteChildren = {
  BrandLoginRoute: BrandLoginRoute,
  BrandOnboardingRoute: BrandOnboardingRoute,
}

const BrandRouteWithChildren = BrandRoute._addFileChildren(BrandRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BrandRoute: BrandRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
