/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as BrandRouteImport } from './routes/_brand'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as BrandLoginRouteImport } from './routes/_brand/login'
import { Route as BrandOnboardingRouteImport } from './routes/_brand/onboarding'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedProjectsProject_idRouteImport } from './routes/_authenticated/projects/$project_id'
import { Route as AuthenticatedProjectsImportRouteImport } from './routes/_authenticated/projects/import'
import { Route as AuthenticatedResourcesIndexRouteImport } from './routes/_authenticated/resources/index'
import { Route as AuthenticatedResourcesResourceRouteImport } from './routes/_authenticated/resources/$resource'
import { Route as AuthenticatedProjectsProject_idIndexRouteImport } from './routes/_authenticated/projects/$project_id/index'
import { Route as AuthenticatedProjectsProject_idDeploymentConfigRouteImport } from './routes/_authenticated/projects/$project_id/deployment-config'
import { Route as AuthenticatedProjectsProject_idDeployIndexRouteImport } from './routes/_authenticated/projects/$project_id/deploy/index'
import { Route as AuthenticatedProjectsProject_idDeployDeploy_idRouteImport } from './routes/_authenticated/projects/$project_id/deploy/$deploy_id'
import { Route as AuthenticatedProjectsProject_idDeployPerformanceRouteImport } from './routes/_authenticated/projects/$project_id/deploy/performance'
import { Route as AuthenticatedProjectsProject_idDeployPreviewRouteImport } from './routes/_authenticated/projects/$project_id/deploy/preview'
import { Route as AuthenticatedProjectsProject_idWorkflowsWorkflow_idDesignRouteImport } from './routes/_authenticated/projects/$project_id/workflows/$workflow_id/design'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/_brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const BrandLoginRoute = BrandLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => BrandRoute,
} as any)
const BrandOnboardingRoute = BrandOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => BrandRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProject_idRoute =
  AuthenticatedProjectsProject_idRouteImport.update({
    id: '/projects/$project_id',
    path: '/projects/$project_id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsImportRoute =
  AuthenticatedProjectsImportRouteImport.update({
    id: '/projects/import',
    path: '/projects/import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResourcesIndexRoute =
  AuthenticatedResourcesIndexRouteImport.update({
    id: '/resources/',
    path: '/resources/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResourcesResourceRoute =
  AuthenticatedResourcesResourceRouteImport.update({
    id: '/resources/$resource',
    path: '/resources/$resource',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProject_idIndexRoute =
  AuthenticatedProjectsProject_idIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProject_idRoute,
  } as any)
const AuthenticatedProjectsProject_idDeploymentConfigRoute =
  AuthenticatedProjectsProject_idDeploymentConfigRouteImport.update({
    id: '/deployment-config',
    path: '/deployment-config',
    getParentRoute: () => AuthenticatedProjectsProject_idRoute,
  } as any)
const AuthenticatedProjectsProject_idDeployIndexRoute =
  AuthenticatedProjectsProject_idDeployIndexRouteImport.update({
    id: '/deploy/',
    path: '/deploy/',
    getParentRoute: () => AuthenticatedProjectsProject_idRoute,
  } as any)
const AuthenticatedProjectsProject_idDeployDeploy_idRoute =
  AuthenticatedProjectsProject_idDeployDeploy_idRouteImport.update({
    id: '/deploy/$deploy_id',
    path: '/deploy/$deploy_id',
    getParentRoute: () => AuthenticatedProjectsProject_idRoute,
  } as any)
const AuthenticatedProjectsProject_idDeployPerformanceRoute =
  AuthenticatedProjectsProject_idDeployPerformanceRouteImport.update({
    id: '/deploy/performance',
    path: '/deploy/performance',
    getParentRoute: () => AuthenticatedProjectsProject_idRoute,
  } as any)
const AuthenticatedProjectsProject_idDeployPreviewRoute =
  AuthenticatedProjectsProject_idDeployPreviewRouteImport.update({
    id: '/deploy/preview',
    path: '/deploy/preview',
    getParentRoute: () => AuthenticatedProjectsProject_idRoute,
  } as any)
const AuthenticatedProjectsProject_idWorkflowsWorkflow_idDesignRoute =
  AuthenticatedProjectsProject_idWorkflowsWorkflow_idDesignRouteImport.update({
    id: '/workflows/$workflow_id/design',
    path: '/workflows/$workflow_id/design',
    getParentRoute: () => AuthenticatedProjectsProject_idRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof BrandLoginRoute
  '/onboarding': typeof BrandOnboardingRoute
  '/projects/$project_id': typeof AuthenticatedProjectsProject_idRouteWithChildren
  '/projects/import': typeof AuthenticatedProjectsImportRoute
  '/resources/$resource': typeof AuthenticatedResourcesResourceRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/resources/': typeof AuthenticatedResourcesIndexRoute
  '/projects/$project_id/deployment-config': typeof AuthenticatedProjectsProject_idDeploymentConfigRoute
  '/projects/$project_id/': typeof AuthenticatedProjectsProject_idIndexRoute
  '/projects/$project_id/deploy/$deploy_id': typeof AuthenticatedProjectsProject_idDeployDeploy_idRoute
  '/projects/$project_id/deploy/performance': typeof AuthenticatedProjectsProject_idDeployPerformanceRoute
  '/projects/$project_id/deploy/preview': typeof AuthenticatedProjectsProject_idDeployPreviewRoute
  '/projects/$project_id/deploy/': typeof AuthenticatedProjectsProject_idDeployIndexRoute
  '/projects/$project_id/workflows/$workflow_id/design': typeof AuthenticatedProjectsProject_idWorkflowsWorkflow_idDesignRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof BrandLoginRoute
  '/onboarding': typeof BrandOnboardingRoute
  '/projects/import': typeof AuthenticatedProjectsImportRoute
  '/resources/$resource': typeof AuthenticatedResourcesResourceRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/resources': typeof AuthenticatedResourcesIndexRoute
  '/projects/$project_id/deployment-config': typeof AuthenticatedProjectsProject_idDeploymentConfigRoute
  '/projects/$project_id': typeof AuthenticatedProjectsProject_idIndexRoute
  '/projects/$project_id/deploy/$deploy_id': typeof AuthenticatedProjectsProject_idDeployDeploy_idRoute
  '/projects/$project_id/deploy/performance': typeof AuthenticatedProjectsProject_idDeployPerformanceRoute
  '/projects/$project_id/deploy/preview': typeof AuthenticatedProjectsProject_idDeployPreviewRoute
  '/projects/$project_id/deploy': typeof AuthenticatedProjectsProject_idDeployIndexRoute
  '/projects/$project_id/workflows/$workflow_id/design': typeof AuthenticatedProjectsProject_idWorkflowsWorkflow_idDesignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_brand': typeof BrandRouteWithChildren
  '/_brand/login': typeof BrandLoginRoute
  '/_brand/onboarding': typeof BrandOnboardingRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/projects/$project_id': typeof AuthenticatedProjectsProject_idRouteWithChildren
  '/_authenticated/projects/import': typeof AuthenticatedProjectsImportRoute
  '/_authenticated/resources/$resource': typeof AuthenticatedResourcesResourceRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/resources/': typeof AuthenticatedResourcesIndexRoute
  '/_authenticated/projects/$project_id/deployment-config': typeof AuthenticatedProjectsProject_idDeploymentConfigRoute
  '/_authenticated/projects/$project_id/': typeof AuthenticatedProjectsProject_idIndexRoute
  '/_authenticated/projects/$project_id/deploy/$deploy_id': typeof AuthenticatedProjectsProject_idDeployDeploy_idRoute
  '/_authenticated/projects/$project_id/deploy/performance': typeof AuthenticatedProjectsProject_idDeployPerformanceRoute
  '/_authenticated/projects/$project_id/deploy/preview': typeof AuthenticatedProjectsProject_idDeployPreviewRoute
  '/_authenticated/projects/$project_id/deploy/': typeof AuthenticatedProjectsProject_idDeployIndexRoute
  '/_authenticated/projects/$project_id/workflows/$workflow_id/design': typeof AuthenticatedProjectsProject_idWorkflowsWorkflow_idDesignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/projects/$project_id'
    | '/projects/import'
    | '/resources/$resource'
    | '/projects/'
    | '/resources/'
    | '/projects/$project_id/deployment-config'
    | '/projects/$project_id/'
    | '/projects/$project_id/deploy/$deploy_id'
    | '/projects/$project_id/deploy/performance'
    | '/projects/$project_id/deploy/preview'
    | '/projects/$project_id/deploy/'
    | '/projects/$project_id/workflows/$workflow_id/design'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/projects/import'
    | '/resources/$resource'
    | '/projects'
    | '/resources'
    | '/projects/$project_id/deployment-config'
    | '/projects/$project_id'
    | '/projects/$project_id/deploy/$deploy_id'
    | '/projects/$project_id/deploy/performance'
    | '/projects/$project_id/deploy/preview'
    | '/projects/$project_id/deploy'
    | '/projects/$project_id/workflows/$workflow_id/design'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_brand'
    | '/_brand/login'
    | '/_brand/onboarding'
    | '/_authenticated/'
    | '/_authenticated/projects/$project_id'
    | '/_authenticated/projects/import'
    | '/_authenticated/resources/$resource'
    | '/_authenticated/projects/'
    | '/_authenticated/resources/'
    | '/_authenticated/projects/$project_id/deployment-config'
    | '/_authenticated/projects/$project_id/'
    | '/_authenticated/projects/$project_id/deploy/$deploy_id'
    | '/_authenticated/projects/$project_id/deploy/performance'
    | '/_authenticated/projects/$project_id/deploy/preview'
    | '/_authenticated/projects/$project_id/deploy/'
    | '/_authenticated/projects/$project_id/workflows/$workflow_id/design'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BrandRoute: typeof BrandRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_brand': {
      id: '/_brand'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_brand/login': {
      id: '/_brand/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof BrandLoginRouteImport
      parentRoute: typeof BrandRoute
    }
    '/_brand/onboarding': {
      id: '/_brand/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof BrandOnboardingRouteImport
      parentRoute: typeof BrandRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$project_id': {
      id: '/_authenticated/projects/$project_id'
      path: '/projects/$project_id'
      fullPath: '/projects/$project_id'
      preLoaderRoute: typeof AuthenticatedProjectsProject_idRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/import': {
      id: '/_authenticated/projects/import'
      path: '/projects/import'
      fullPath: '/projects/import'
      preLoaderRoute: typeof AuthenticatedProjectsImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resources/': {
      id: '/_authenticated/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof AuthenticatedResourcesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resources/$resource': {
      id: '/_authenticated/resources/$resource'
      path: '/resources/$resource'
      fullPath: '/resources/$resource'
      preLoaderRoute: typeof AuthenticatedResourcesResourceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$project_id/': {
      id: '/_authenticated/projects/$project_id/'
      path: '/'
      fullPath: '/projects/$project_id/'
      preLoaderRoute: typeof AuthenticatedProjectsProject_idIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProject_idRoute
    }
    '/_authenticated/projects/$project_id/deployment-config': {
      id: '/_authenticated/projects/$project_id/deployment-config'
      path: '/deployment-config'
      fullPath: '/projects/$project_id/deployment-config'
      preLoaderRoute: typeof AuthenticatedProjectsProject_idDeploymentConfigRouteImport
      parentRoute: typeof AuthenticatedProjectsProject_idRoute
    }
    '/_authenticated/projects/$project_id/deploy/': {
      id: '/_authenticated/projects/$project_id/deploy/'
      path: '/deploy'
      fullPath: '/projects/$project_id/deploy/'
      preLoaderRoute: typeof AuthenticatedProjectsProject_idDeployIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProject_idRoute
    }
    '/_authenticated/projects/$project_id/deploy/$deploy_id': {
      id: '/_authenticated/projects/$project_id/deploy/$deploy_id'
      path: '/deploy/$deploy_id'
      fullPath: '/projects/$project_id/deploy/$deploy_id'
      preLoaderRoute: typeof AuthenticatedProjectsProject_idDeployDeploy_idRouteImport
      parentRoute: typeof AuthenticatedProjectsProject_idRoute
    }
    '/_authenticated/projects/$project_id/deploy/performance': {
      id: '/_authenticated/projects/$project_id/deploy/performance'
      path: '/deploy/performance'
      fullPath: '/projects/$project_id/deploy/performance'
      preLoaderRoute: typeof AuthenticatedProjectsProject_idDeployPerformanceRouteImport
      parentRoute: typeof AuthenticatedProjectsProject_idRoute
    }
    '/_authenticated/projects/$project_id/deploy/preview': {
      id: '/_authenticated/projects/$project_id/deploy/preview'
      path: '/deploy/preview'
      fullPath: '/projects/$project_id/deploy/preview'
      preLoaderRoute: typeof AuthenticatedProjectsProject_idDeployPreviewRouteImport
      parentRoute: typeof AuthenticatedProjectsProject_idRoute
    }
    '/_authenticated/projects/$project_id/workflows/$workflow_id/design': {
      id: '/_authenticated/projects/$project_id/workflows/$workflow_id/design'
      path: '/workflows/$workflow_id/design'
      fullPath: '/projects/$project_id/workflows/$workflow_id/design'
      preLoaderRoute: typeof AuthenticatedProjectsProject_idWorkflowsWorkflow_idDesignRouteImport
      parentRoute: typeof AuthenticatedProjectsProject_idRoute
    }
  }
}

interface AuthenticatedProjectsProject_idRouteChildren {
  AuthenticatedProjectsProject_idDeploymentConfigRoute: typeof AuthenticatedProjectsProject_idDeploymentConfigRoute
  AuthenticatedProjectsProject_idIndexRoute: typeof AuthenticatedProjectsProject_idIndexRoute
  AuthenticatedProjectsProject_idDeployDeploy_idRoute: typeof AuthenticatedProjectsProject_idDeployDeploy_idRoute
  AuthenticatedProjectsProject_idDeployPerformanceRoute: typeof AuthenticatedProjectsProject_idDeployPerformanceRoute
  AuthenticatedProjectsProject_idDeployPreviewRoute: typeof AuthenticatedProjectsProject_idDeployPreviewRoute
  AuthenticatedProjectsProject_idDeployIndexRoute: typeof AuthenticatedProjectsProject_idDeployIndexRoute
  AuthenticatedProjectsProject_idWorkflowsWorkflow_idDesignRoute: typeof AuthenticatedProjectsProject_idWorkflowsWorkflow_idDesignRoute
}

const AuthenticatedProjectsProject_idRouteChildren: AuthenticatedProjectsProject_idRouteChildren =
  {
    AuthenticatedProjectsProject_idDeploymentConfigRoute:
      AuthenticatedProjectsProject_idDeploymentConfigRoute,
    AuthenticatedProjectsProject_idIndexRoute:
      AuthenticatedProjectsProject_idIndexRoute,
    AuthenticatedProjectsProject_idDeployDeploy_idRoute:
      AuthenticatedProjectsProject_idDeployDeploy_idRoute,
    AuthenticatedProjectsProject_idDeployPerformanceRoute:
      AuthenticatedProjectsProject_idDeployPerformanceRoute,
    AuthenticatedProjectsProject_idDeployPreviewRoute:
      AuthenticatedProjectsProject_idDeployPreviewRoute,
    AuthenticatedProjectsProject_idDeployIndexRoute:
      AuthenticatedProjectsProject_idDeployIndexRoute,
    AuthenticatedProjectsProject_idWorkflowsWorkflow_idDesignRoute:
      AuthenticatedProjectsProject_idWorkflowsWorkflow_idDesignRoute,
  }

const AuthenticatedProjectsProject_idRouteWithChildren =
  AuthenticatedProjectsProject_idRoute._addFileChildren(
    AuthenticatedProjectsProject_idRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProjectsProject_idRoute: typeof AuthenticatedProjectsProject_idRouteWithChildren
  AuthenticatedProjectsImportRoute: typeof AuthenticatedProjectsImportRoute
  AuthenticatedResourcesResourceRoute: typeof AuthenticatedResourcesResourceRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedResourcesIndexRoute: typeof AuthenticatedResourcesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProjectsProject_idRoute:
    AuthenticatedProjectsProject_idRouteWithChildren,
  AuthenticatedProjectsImportRoute: AuthenticatedProjectsImportRoute,
  AuthenticatedResourcesResourceRoute: AuthenticatedResourcesResourceRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedResourcesIndexRoute: AuthenticatedResourcesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface BrandRouteChildren {
  BrandLoginRoute: typeof BrandLoginRoute
  BrandOnboardingRoute: typeof BrandOnboardingRoute
}

const BrandRouteChildren: BrandRouteChildren = {
  BrandLoginRoute: BrandLoginRoute,
  BrandOnboardingRoute: BrandOnboardingRoute,
}

const BrandRouteWithChildren = BrandRoute._addFileChildren(BrandRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BrandRoute: BrandRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
