/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as BrandRouteImport } from './routes/_brand'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as BrandLoginRouteImport } from './routes/_brand/login'
import { Route as BrandOnboardingRouteImport } from './routes/_brand/onboarding'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedProjectsProject_idRouteImport } from './routes/_authenticated/projects/$project_id'
import { Route as AuthenticatedProjectsProject_idIndexRouteImport } from './routes/_authenticated/projects/$project_id/index'
import { Route as AuthenticatedProjectsProject_idErrorsRouteImport } from './routes/_authenticated/projects/$project_id/errors'
import { Route as AuthenticatedProjectsProject_idLlmRouteImport } from './routes/_authenticated/projects/$project_id/llm'
import { Route as AuthenticatedProjectsProject_idLogsRouteImport } from './routes/_authenticated/projects/$project_id/logs'
import { Route as AuthenticatedProjectsProject_idMetricsRouteImport } from './routes/_authenticated/projects/$project_id/metrics'
import { Route as AuthenticatedProjectsProject_idMonitoringRouteImport } from './routes/_authenticated/projects/$project_id/monitoring'
import { Route as AuthenticatedProjectsProject_idPromptsRouteImport } from './routes/_authenticated/projects/$project_id/prompts'
import { Route as AuthenticatedProjectsProject_idScalingRouteImport } from './routes/_authenticated/projects/$project_id/scaling'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/_brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const BrandLoginRoute = BrandLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => BrandRoute,
} as any)
const BrandOnboardingRoute = BrandOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => BrandRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProject_idRoute =
  AuthenticatedProjectsProject_idRouteImport.update({
    id: '/projects/$project_id',
    path: '/projects/$project_id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProject_idIndexRoute =
  AuthenticatedProjectsProject_idIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProject_idRoute,
  } as any)
const AuthenticatedProjectsProject_idErrorsRoute =
  AuthenticatedProjectsProject_idErrorsRouteImport.update({
    id: '/errors',
    path: '/errors',
    getParentRoute: () => AuthenticatedProjectsProject_idRoute,
  } as any)
const AuthenticatedProjectsProject_idLlmRoute =
  AuthenticatedProjectsProject_idLlmRouteImport.update({
    id: '/llm',
    path: '/llm',
    getParentRoute: () => AuthenticatedProjectsProject_idRoute,
  } as any)
const AuthenticatedProjectsProject_idLogsRoute =
  AuthenticatedProjectsProject_idLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedProjectsProject_idRoute,
  } as any)
const AuthenticatedProjectsProject_idMetricsRoute =
  AuthenticatedProjectsProject_idMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => AuthenticatedProjectsProject_idRoute,
  } as any)
const AuthenticatedProjectsProject_idMonitoringRoute =
  AuthenticatedProjectsProject_idMonitoringRouteImport.update({
    id: '/monitoring',
    path: '/monitoring',
    getParentRoute: () => AuthenticatedProjectsProject_idRoute,
  } as any)
const AuthenticatedProjectsProject_idPromptsRoute =
  AuthenticatedProjectsProject_idPromptsRouteImport.update({
    id: '/prompts',
    path: '/prompts',
    getParentRoute: () => AuthenticatedProjectsProject_idRoute,
  } as any)
const AuthenticatedProjectsProject_idScalingRoute =
  AuthenticatedProjectsProject_idScalingRouteImport.update({
    id: '/scaling',
    path: '/scaling',
    getParentRoute: () => AuthenticatedProjectsProject_idRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof BrandLoginRoute
  '/onboarding': typeof BrandOnboardingRoute
  '/projects/$project_id': typeof AuthenticatedProjectsProject_idRouteWithChildren
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/projects/$project_id/errors': typeof AuthenticatedProjectsProject_idErrorsRoute
  '/projects/$project_id/llm': typeof AuthenticatedProjectsProject_idLlmRoute
  '/projects/$project_id/logs': typeof AuthenticatedProjectsProject_idLogsRoute
  '/projects/$project_id/metrics': typeof AuthenticatedProjectsProject_idMetricsRoute
  '/projects/$project_id/monitoring': typeof AuthenticatedProjectsProject_idMonitoringRoute
  '/projects/$project_id/prompts': typeof AuthenticatedProjectsProject_idPromptsRoute
  '/projects/$project_id/scaling': typeof AuthenticatedProjectsProject_idScalingRoute
  '/projects/$project_id/': typeof AuthenticatedProjectsProject_idIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof BrandLoginRoute
  '/onboarding': typeof BrandOnboardingRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/projects/$project_id/errors': typeof AuthenticatedProjectsProject_idErrorsRoute
  '/projects/$project_id/llm': typeof AuthenticatedProjectsProject_idLlmRoute
  '/projects/$project_id/logs': typeof AuthenticatedProjectsProject_idLogsRoute
  '/projects/$project_id/metrics': typeof AuthenticatedProjectsProject_idMetricsRoute
  '/projects/$project_id/monitoring': typeof AuthenticatedProjectsProject_idMonitoringRoute
  '/projects/$project_id/prompts': typeof AuthenticatedProjectsProject_idPromptsRoute
  '/projects/$project_id/scaling': typeof AuthenticatedProjectsProject_idScalingRoute
  '/projects/$project_id': typeof AuthenticatedProjectsProject_idIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_brand': typeof BrandRouteWithChildren
  '/_brand/login': typeof BrandLoginRoute
  '/_brand/onboarding': typeof BrandOnboardingRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/projects/$project_id': typeof AuthenticatedProjectsProject_idRouteWithChildren
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/projects/$project_id/errors': typeof AuthenticatedProjectsProject_idErrorsRoute
  '/_authenticated/projects/$project_id/llm': typeof AuthenticatedProjectsProject_idLlmRoute
  '/_authenticated/projects/$project_id/logs': typeof AuthenticatedProjectsProject_idLogsRoute
  '/_authenticated/projects/$project_id/metrics': typeof AuthenticatedProjectsProject_idMetricsRoute
  '/_authenticated/projects/$project_id/monitoring': typeof AuthenticatedProjectsProject_idMonitoringRoute
  '/_authenticated/projects/$project_id/prompts': typeof AuthenticatedProjectsProject_idPromptsRoute
  '/_authenticated/projects/$project_id/scaling': typeof AuthenticatedProjectsProject_idScalingRoute
  '/_authenticated/projects/$project_id/': typeof AuthenticatedProjectsProject_idIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/projects/$project_id'
    | '/projects/'
    | '/projects/$project_id/errors'
    | '/projects/$project_id/llm'
    | '/projects/$project_id/logs'
    | '/projects/$project_id/metrics'
    | '/projects/$project_id/monitoring'
    | '/projects/$project_id/prompts'
    | '/projects/$project_id/scaling'
    | '/projects/$project_id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/projects'
    | '/projects/$project_id/errors'
    | '/projects/$project_id/llm'
    | '/projects/$project_id/logs'
    | '/projects/$project_id/metrics'
    | '/projects/$project_id/monitoring'
    | '/projects/$project_id/prompts'
    | '/projects/$project_id/scaling'
    | '/projects/$project_id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_brand'
    | '/_brand/login'
    | '/_brand/onboarding'
    | '/_authenticated/'
    | '/_authenticated/projects/$project_id'
    | '/_authenticated/projects/'
    | '/_authenticated/projects/$project_id/errors'
    | '/_authenticated/projects/$project_id/llm'
    | '/_authenticated/projects/$project_id/logs'
    | '/_authenticated/projects/$project_id/metrics'
    | '/_authenticated/projects/$project_id/monitoring'
    | '/_authenticated/projects/$project_id/prompts'
    | '/_authenticated/projects/$project_id/scaling'
    | '/_authenticated/projects/$project_id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BrandRoute: typeof BrandRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_brand': {
      id: '/_brand'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_brand/login': {
      id: '/_brand/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof BrandLoginRouteImport
      parentRoute: typeof BrandRoute
    }
    '/_brand/onboarding': {
      id: '/_brand/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof BrandOnboardingRouteImport
      parentRoute: typeof BrandRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$project_id': {
      id: '/_authenticated/projects/$project_id'
      path: '/projects/$project_id'
      fullPath: '/projects/$project_id'
      preLoaderRoute: typeof AuthenticatedProjectsProject_idRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$project_id/': {
      id: '/_authenticated/projects/$project_id/'
      path: '/'
      fullPath: '/projects/$project_id/'
      preLoaderRoute: typeof AuthenticatedProjectsProject_idIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProject_idRoute
    }
    '/_authenticated/projects/$project_id/errors': {
      id: '/_authenticated/projects/$project_id/errors'
      path: '/errors'
      fullPath: '/projects/$project_id/errors'
      preLoaderRoute: typeof AuthenticatedProjectsProject_idErrorsRouteImport
      parentRoute: typeof AuthenticatedProjectsProject_idRoute
    }
    '/_authenticated/projects/$project_id/llm': {
      id: '/_authenticated/projects/$project_id/llm'
      path: '/llm'
      fullPath: '/projects/$project_id/llm'
      preLoaderRoute: typeof AuthenticatedProjectsProject_idLlmRouteImport
      parentRoute: typeof AuthenticatedProjectsProject_idRoute
    }
    '/_authenticated/projects/$project_id/logs': {
      id: '/_authenticated/projects/$project_id/logs'
      path: '/logs'
      fullPath: '/projects/$project_id/logs'
      preLoaderRoute: typeof AuthenticatedProjectsProject_idLogsRouteImport
      parentRoute: typeof AuthenticatedProjectsProject_idRoute
    }
    '/_authenticated/projects/$project_id/metrics': {
      id: '/_authenticated/projects/$project_id/metrics'
      path: '/metrics'
      fullPath: '/projects/$project_id/metrics'
      preLoaderRoute: typeof AuthenticatedProjectsProject_idMetricsRouteImport
      parentRoute: typeof AuthenticatedProjectsProject_idRoute
    }
    '/_authenticated/projects/$project_id/monitoring': {
      id: '/_authenticated/projects/$project_id/monitoring'
      path: '/monitoring'
      fullPath: '/projects/$project_id/monitoring'
      preLoaderRoute: typeof AuthenticatedProjectsProject_idMonitoringRouteImport
      parentRoute: typeof AuthenticatedProjectsProject_idRoute
    }
    '/_authenticated/projects/$project_id/prompts': {
      id: '/_authenticated/projects/$project_id/prompts'
      path: '/prompts'
      fullPath: '/projects/$project_id/prompts'
      preLoaderRoute: typeof AuthenticatedProjectsProject_idPromptsRouteImport
      parentRoute: typeof AuthenticatedProjectsProject_idRoute
    }
    '/_authenticated/projects/$project_id/scaling': {
      id: '/_authenticated/projects/$project_id/scaling'
      path: '/scaling'
      fullPath: '/projects/$project_id/scaling'
      preLoaderRoute: typeof AuthenticatedProjectsProject_idScalingRouteImport
      parentRoute: typeof AuthenticatedProjectsProject_idRoute
    }
  }
}

interface AuthenticatedProjectsProject_idRouteChildren {
  AuthenticatedProjectsProject_idErrorsRoute: typeof AuthenticatedProjectsProject_idErrorsRoute
  AuthenticatedProjectsProject_idLlmRoute: typeof AuthenticatedProjectsProject_idLlmRoute
  AuthenticatedProjectsProject_idLogsRoute: typeof AuthenticatedProjectsProject_idLogsRoute
  AuthenticatedProjectsProject_idMetricsRoute: typeof AuthenticatedProjectsProject_idMetricsRoute
  AuthenticatedProjectsProject_idMonitoringRoute: typeof AuthenticatedProjectsProject_idMonitoringRoute
  AuthenticatedProjectsProject_idPromptsRoute: typeof AuthenticatedProjectsProject_idPromptsRoute
  AuthenticatedProjectsProject_idScalingRoute: typeof AuthenticatedProjectsProject_idScalingRoute
  AuthenticatedProjectsProject_idIndexRoute: typeof AuthenticatedProjectsProject_idIndexRoute
}

const AuthenticatedProjectsProject_idRouteChildren: AuthenticatedProjectsProject_idRouteChildren =
  {
    AuthenticatedProjectsProject_idErrorsRoute:
      AuthenticatedProjectsProject_idErrorsRoute,
    AuthenticatedProjectsProject_idLlmRoute:
      AuthenticatedProjectsProject_idLlmRoute,
    AuthenticatedProjectsProject_idLogsRoute:
      AuthenticatedProjectsProject_idLogsRoute,
    AuthenticatedProjectsProject_idMetricsRoute:
      AuthenticatedProjectsProject_idMetricsRoute,
    AuthenticatedProjectsProject_idMonitoringRoute:
      AuthenticatedProjectsProject_idMonitoringRoute,
    AuthenticatedProjectsProject_idPromptsRoute:
      AuthenticatedProjectsProject_idPromptsRoute,
    AuthenticatedProjectsProject_idScalingRoute:
      AuthenticatedProjectsProject_idScalingRoute,
    AuthenticatedProjectsProject_idIndexRoute:
      AuthenticatedProjectsProject_idIndexRoute,
  }

const AuthenticatedProjectsProject_idRouteWithChildren =
  AuthenticatedProjectsProject_idRoute._addFileChildren(
    AuthenticatedProjectsProject_idRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProjectsProject_idRoute: typeof AuthenticatedProjectsProject_idRouteWithChildren
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProjectsProject_idRoute:
    AuthenticatedProjectsProject_idRouteWithChildren,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface BrandRouteChildren {
  BrandLoginRoute: typeof BrandLoginRoute
  BrandOnboardingRoute: typeof BrandOnboardingRoute
}

const BrandRouteChildren: BrandRouteChildren = {
  BrandLoginRoute: BrandLoginRoute,
  BrandOnboardingRoute: BrandOnboardingRoute,
}

const BrandRouteWithChildren = BrandRoute._addFileChildren(BrandRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BrandRoute: BrandRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
