import type { ResourceOverview } from './resources.types';

export const resourceCpuMock: ResourceOverview = {
  focus: {
    id: 'cpu',
    label: 'CPU',
    description: 'Fleet-wide CPU allocation, cost & utilization',
    usage_unit: 'hrs',
    allocation_unit: 'cores',
    spend: 612,
    spend_delta: { value: 8.4, direction: 'increase' },
    cost_series: [38, 79, 134, 182, 233, 281, 327, 371, 413, 456, 499, 535, 567, 589, 603, 612],
  },
  projects: [
    {
      id: 'parser',
      name: 'Document Parser',
      usage: 64,
      allocation: 4,
      utilization_pct: 82,
      idle_minutes: 84,
      cost_share: 245,
    },
    {
      id: 'fraud',
      name: 'Fraud Screen',
      usage: 40,
      allocation: 3,
      utilization_pct: 74,
      idle_minutes: 42,
      cost_share: 153,
    },
    {
      id: 'rerank',
      name: 'Search Reranker',
      usage: 28,
      allocation: 2,
      utilization_pct: 66,
      idle_minutes: 28,
      cost_share: 107,
    },
    {
      id: 'router',
      name: 'Request Router',
      usage: 18,
      allocation: 1,
      utilization_pct: 58,
      idle_minutes: 56,
      cost_share: 69,
    },
    {
      id: 'triage',
      name: 'Email Triage',
      usage: 6,
      allocation: 1,
      utilization_pct: 41,
      idle_minutes: 14,
      cost_share: 23,
    },
    {
      id: 'onboard',
      name: 'Onboarding Bot',
      usage: 4,
      allocation: 1,
      utilization_pct: 29,
      idle_minutes: 7,
      cost_share: 15,
    },
  ],
  requests: [
    {
      id: 'req_4f8a21c0',
      project_id: 'parser',
      project_name: 'Document Parser',
      usage: 8.4,
      run_time_ms: 3120,
      latency_ms: 412,
      status: 'ok',
      time_label: '2 min ago',
    },
    {
      id: 'req_9b3e07d5',
      project_id: 'fraud',
      project_name: 'Fraud Screen',
      usage: 6.7,
      run_time_ms: 2440,
      latency_ms: 380,
      status: 'ok',
      time_label: '8 min ago',
    },
    {
      id: 'req_1c6d44af',
      project_id: 'rerank',
      project_name: 'Search Reranker',
      usage: 5.2,
      run_time_ms: 1820,
      latency_ms: 210,
      status: 'running',
      time_label: 'just now',
    },
    {
      id: 'req_72a0e9b1',
      project_id: 'router',
      project_name: 'Request Router',
      usage: 4.1,
      run_time_ms: 1280,
      latency_ms: 290,
      status: 'ok',
      time_label: '5 min ago',
    },
    {
      id: 'req_e5510cd8',
      project_id: 'parser',
      project_name: 'Document Parser',
      usage: 3.6,
      run_time_ms: 2010,
      latency_ms: 520,
      status: 'error',
      time_label: '12 min ago',
    },
    {
      id: 'req_a8f2b370',
      project_id: 'triage',
      project_name: 'Email Triage',
      usage: 2.2,
      run_time_ms: 940,
      latency_ms: 140,
      status: 'ok',
      time_label: '15 min ago',
    },
  ],
};
